### PR TITLE
fix category translation

### PR DESCRIPTION
**Pull request by resslinger**
| Q                         | A
| ------------------------- | ---
| issue or Enhancement      | issue
| Changelog updated?        | no
| License                   | MIT

#### What's in this PR?

This PR fix the category translation.

#### Checklist

- [ ] Updated CHANGELOG.md to describe BC breaks / deprecations | new feature | bugfix

### CODE REVIEW

**Comment by resslinger** [comment]
@BernhardK91 Can you please merge this?

**Comment by BernhardK91** [comment]
@resslinger I am very sorry for the delay. I did not get a notification for the PR. Thanks a lot for your contribution. 

I was not able to find any source that Shopware changed there field names. Do you have a source for that needed change?

**Comment by resslinger** [comment]
@BernhardK91 I found the forum entry from 2020 and added a PR to the main repo: https://forum.plentymarkets.com/t/arvatis-shopware-connector-kategorien-werden-nicht-mehrsprachig-abgeglichen/581836

We have the PR since 2020 live. I will check, why the category translation was change from Shopware.
The main change in this PR is, that the db field for the category name is in "description" and not in "name" like before this change.

**Comment by BernhardK91** [comment]
@resslinger I have tested that in one of my environments without that change. I am not able to reproduce any problem with categories sync. Can you give me some steps to reproduce?

You are right, that the database field is named "description", but the API documentation (at least for REST API) is still calling it "name":
https://developers.shopware.com/developers-guide/rest-api/examples/category/#example-1-creating-a-category

**Comment by resslinger** [comment]
@BernhardK91 I will check this again.

**Comment by resslinger** [comment]
@BernhardK91 The translation of categories is not stored over api, but directly to the translation database table. We tested it on our site and works only with this PR.

**Comment by BernhardK91** [comment]
@resslinger Thank you for the information. Then I will merge the PR, as you have checked that it is required.

**Pull request merged**
